/*
 * Copyright (C) 2016  (See AUTHORS)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* Generated By:JavaCC: Do not edit this line. LTLParserConstants.java */
package ltl.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LTLParserConstants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int FOP = 5;
    /**
     * RegularExpression Id.
     */
    int VOP = 6;
    /**
     * RegularExpression Id.
     */
    int ROP = 7;
    /**
     * RegularExpression Id.
     */
    int WOP = 8;
    /**
     * RegularExpression Id.
     */
    int GOP = 9;
    /**
     * RegularExpression Id.
     */
    int XOP = 10;
    /**
     * RegularExpression Id.
     */
    int NEG = 11;
    /**
     * RegularExpression Id.
     */
    int UOP = 12;
    /**
     * RegularExpression Id.
     */
    int AND = 13;
    /**
     * RegularExpression Id.
     */
    int OR = 14;
    /**
     * RegularExpression Id.
     */
    int LPAR = 15;
    /**
     * RegularExpression Id.
     */
    int RPAR = 16;
    /**
     * RegularExpression Id.
     */
    int TRUE = 17;
    /**
     * RegularExpression Id.
     */
    int FALSE = 18;
    /**
     * RegularExpression Id.
     */
    int ID = 19;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;

    /**
     * Literal token values.
     */
    String[] tokenImage = {
            "<EOF>",
            "\" \"",
            "\"\\r\"",
            "\"\\t\"",
            "\"\\n\"",
            "\"F\"",
            "\"V\"",
            "\"R\"",
            "\"W\"",
            "\"G\"",
            "\"X\"",
            "\"!\"",
            "\"U\"",
            "\"&\"",
            "\"|\"",
            "\"(\"",
            "\")\"",
            "<TRUE>",
            "<FALSE>",
            "<ID>",
    };

}
