#!/bin/bash
#
# Copyright (C) 2016 - 2021  (See AUTHORS)
#
# This file is part of Owl.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# expects $1 = input tlsf file
DIR=$(dirname "$0")/
SYFCO="${DIR}../syfco/syfco"
OWL_BIN="${DIR}distro/bin/"

# call syfco
formulas=$(${SYFCO} -f ltlxba -m fully "$1")

# syfco will return a list of formulas
# we will feed them into owl one by one
IFS=';' read -ra FMLS <<< "${formulas}"
for f in "${FMLS[@]}"; do
  echo "Constructing automaton for formula ${f}"
  # call owl
  echo "${f}" | ${OWL_BIN}/ltl2dpa
done
