#!/bin/bash
#
# Copyright (C) 2016 - 2021  (See AUTHORS)
#
# This file is part of Owl.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# expects $1 = input tlsf file
DIR=`dirname $0`/
SYFCO="${DIR}../syfco/syfco"
OWL_BIN="${DIR}distro/bin/"

# call syfco
base=$(basename $1)
temp="${DIR}"
formulas=$(${SYFCO} -f ltlxba "$1" -m fully -pf "${temp}${base}.part")

# syfco will return a list of formulas separated by
# ; and we will feed them all to owl.synth
while IFS= read -r line
do
    uncontrollable="${line}"
    break
done < "${temp}${base}.part"
prefix=".inputs "
uncontrollable=${uncontrollable#$prefix}
echo "${formulas}" | sed "s/;/\\`echo -e '\n\r'`/g" | ${OWL_BIN}/synth -u ${uncontrollable}
