---

name: Linter
on:
  push:
    branches:
      - 'main'
      - 'release-*'
  pull_request:
    branches:
      - 'main'
      - 'release-*'

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          # We use Google Jave Format.
          VALIDATE_JAVA: false
          # Deactive until Java 17 is supported.
          VALIDATE_GOOGLE_JAVA_FORMAT: false
          # Too sensitive.
          VALIDATE_JSCPD: false
